Search.appendIndex(
    [
                {
            "fqsen": "\\bind_params_dynamic\u0028\u0029",
            "name": "bind_params_dynamic",
            "summary": "",
            "url": "namespaces/default.html#function_bind_params_dynamic"
        },                {
            "fqsen": "\\validaCPF\u0028\u0029",
            "name": "validaCPF",
            "summary": "",
            "url": "namespaces/default.html#function_validaCPF"
        },                {
            "fqsen": "\\env\u0028\u0029",
            "name": "env",
            "summary": "Retorna\u0020variavel\u0020de\u0020ambiente\u0020ou\u0020valor\u0020padrao",
            "url": "namespaces/default.html#function_env"
        },                {
            "fqsen": "\\csrf_token\u0028\u0029",
            "name": "csrf_token",
            "summary": "",
            "url": "namespaces/default.html#function_csrf_token"
        },                {
            "fqsen": "\\csrf_field\u0028\u0029",
            "name": "csrf_field",
            "summary": "",
            "url": "namespaces/default.html#function_csrf_field"
        },                {
            "fqsen": "\\csrf_validate\u0028\u0029",
            "name": "csrf_validate",
            "summary": "",
            "url": "namespaces/default.html#function_csrf_validate"
        },                {
            "fqsen": "\\flash\u0028\u0029",
            "name": "flash",
            "summary": "",
            "url": "namespaces/default.html#function_flash"
        },                {
            "fqsen": "\\get_flash\u0028\u0029",
            "name": "get_flash",
            "summary": "",
            "url": "namespaces/default.html#function_get_flash"
        },                {
            "fqsen": "\\app_base_path\u0028\u0029",
            "name": "app_base_path",
            "summary": "",
            "url": "namespaces/default.html#function_app_base_path"
        },                {
            "fqsen": "\\app_url\u0028\u0029",
            "name": "app_url",
            "summary": "",
            "url": "namespaces/default.html#function_app_url"
        },                {
            "fqsen": "\\app_absolute_url\u0028\u0029",
            "name": "app_absolute_url",
            "summary": "",
            "url": "namespaces/default.html#function_app_absolute_url"
        },                {
            "fqsen": "\\auth_check\u0028\u0029",
            "name": "auth_check",
            "summary": "",
            "url": "namespaces/default.html#function_auth_check"
        },                {
            "fqsen": "\\admin_check\u0028\u0029",
            "name": "admin_check",
            "summary": "",
            "url": "namespaces/default.html#function_admin_check"
        },                {
            "fqsen": "\\redirect\u0028\u0029",
            "name": "redirect",
            "summary": "",
            "url": "namespaces/default.html#function_redirect"
        },                {
            "fqsen": "\\resumo_home\u0028\u0029",
            "name": "resumo_home",
            "summary": "",
            "url": "namespaces/default.html#function_resumo_home"
        },                {
            "fqsen": "\\anthropic_chat_with_fallback\u0028\u0029",
            "name": "anthropic_chat_with_fallback",
            "summary": "",
            "url": "namespaces/default.html#function_anthropic_chat_with_fallback"
        },                {
            "fqsen": "\\ai_resume_texto\u0028\u0029",
            "name": "ai_resume_texto",
            "summary": "",
            "url": "namespaces/default.html#function_ai_resume_texto"
        },                {
            "fqsen": "\\ai_connect_db_optional\u0028\u0029",
            "name": "ai_connect_db_optional",
            "summary": "",
            "url": "namespaces/default.html#function_ai_connect_db_optional"
        },                {
            "fqsen": "\\ai_catalogo_site_contexto\u0028\u0029",
            "name": "ai_catalogo_site_contexto",
            "summary": "",
            "url": "namespaces/default.html#function_ai_catalogo_site_contexto"
        },                {
            "fqsen": "\\ai_format_inline\u0028\u0029",
            "name": "ai_format_inline",
            "summary": "",
            "url": "namespaces/default.html#function_ai_format_inline"
        },                {
            "fqsen": "\\ai_render_response_html\u0028\u0029",
            "name": "ai_render_response_html",
            "summary": "",
            "url": "namespaces/default.html#function_ai_render_response_html"
        },                {
            "fqsen": "\\resumo_curso\u0028\u0029",
            "name": "resumo_curso",
            "summary": "",
            "url": "namespaces/default.html#function_resumo_curso"
        },                {
            "fqsen": "\\split_lines\u0028\u0029",
            "name": "split_lines",
            "summary": "",
            "url": "namespaces/default.html#function_split_lines"
        },                {
            "fqsen": "\\safe_http_url\u0028\u0029",
            "name": "safe_http_url",
            "summary": "",
            "url": "namespaces/default.html#function_safe_http_url"
        },                {
            "fqsen": "\\resumo_vaga\u0028\u0029",
            "name": "resumo_vaga",
            "summary": "",
            "url": "namespaces/default.html#function_resumo_vaga"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
